--
-- Create a table for public user profiles
CREATE TABLE user_profiles (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  updated_at TIMESTAMP WITH TIME ZONE,
  username TEXT UNIQUE,
  full_name TEXT,
  avatar_url TEXT,
  website TEXT,
  skill_level TEXT,
  CONSTRAINT username_length CHECK (char_length(username) >= 3)
);

--
-- USER BACKGROUNDS
--
CREATE TABLE user_backgrounds (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  updated_at TIMESTAMP WITH TIME ZONE,
  hardware_experience JSONB,
  software_experience JSONB,
  learning_goals JSONB
);

--
-- USER PROGRESS
--
CREATE TABLE user_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  module_id TEXT NOT NULL,
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  score INT,
  time_spent INT -- in minutes
);

--
-- USER PREFERENCES
--
CREATE TABLE user_preferences (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  updated_at TIMESTAMP WITH TIME ZONE,
  preferred_topics TEXT[],
  learning_path_style TEXT -- e.g., 'guided', 'self-driven'
);

--
-- Enable Row Level Security (RLS)
--
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_backgrounds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_preferences ENABLE ROW LEVEL SECURITY;

--
-- Set up policies for user_profiles
--
CREATE POLICY "Public profiles are viewable by everyone."
  ON user_profiles FOR SELECT
  USING ( true );

CREATE POLICY "Users can insert their own profile."
  ON user_profiles FOR INSERT
  WITH CHECK ( auth.uid() = id );

CREATE POLICY "Users can update own profile."
  ON user_profiles FOR UPDATE
  USING ( auth.uid() = id );

--
-- Set up policies for user_backgrounds
--
CREATE POLICY "Users can view their own background."
  ON user_backgrounds FOR SELECT
  USING ( auth.uid() = id );

CREATE POLICY "Users can insert their own background."
  ON user_backgrounds FOR INSERT
  WITH CHECK ( auth.uid() = id );

CREATE POLICY "Users can update their own background."
  ON user_backgrounds FOR UPDATE
  USING ( auth.uid() = id );

--
-- Set up policies for user_progress
--
CREATE POLICY "Users can view their own progress."
  ON user_progress FOR SELECT
  USING ( auth.uid() = user_id );

CREATE POLICY "Users can insert their own progress."
  ON user_progress FOR INSERT
  WITH CHECK ( auth.uid() = user_id );

--
-- Set up policies for user_preferences
--
CREATE POLICY "Users can view their own preferences."
  ON user_preferences FOR SELECT
  USING ( auth.uid() = id );

CREATE POLICY "Users can insert their own preferences."
  ON user_preferences FOR INSERT
  WITH CHECK ( auth.uid() = id );

CREATE POLICY "Users can update their own preferences."
  ON user_preferences FOR UPDATE
  USING ( auth.uid() = id );

--
-- Function to create a public profile on new user signup
--
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.user_profiles (id, username)
  VALUES (new.id, new.email);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

--
-- Trigger to call the function on new user creation
--
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
