/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "AI Humanoid Robotics",
  "tagline": "Learn AI and Robotics",
  "url": "https://shaya9.github.io",
  "baseUrl": "/ai-humanoid-robotics-book/",
  "favicon": "img/favicon.ico",
  "organizationName": "SHAYA9",
  "projectName": "ai-humanoid-robotics-book",
  "onBrokenLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "sidebarPath": "C:\\Users\\SHAYAN\\Desktop\\hackathon\\ai-humanoid-robotics-book\\sidebars.ts",
          "routeBasePath": "/docs"
        },
        "theme": {
          "customCss": "C:\\Users\\SHAYAN\\Desktop\\hackathon\\ai-humanoid-robotics-book\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "title": "AI Humanoid Robotics",
      "logo": {
        "alt": "AI Humanoid Robotics Logo",
        "src": "img/logo.png",
        "srcDark": "img/logo.png",
        "href": "/",
        "target": "_self",
        "width": 35,
        "height": 35
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "📚 Curriculum"
        },
        {
          "href": "https://github.com/SHAYA9/ai-humanoid-robotics-book",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "logo": {
        "alt": "AI Humanoid Robotics Logo",
        "src": "img/logo.png",
        "width": 60,
        "height": 60,
        "href": "https://xpertsphere.vercel.app"
      },
      "copyright": "Copyright © 2025 AI Humanoid Robotics Book. by Xpertsphere",
      "links": [
        {
          "title": "Curriculum",
          "items": [
            {
              "label": "Getting Started",
              "to": "/docs/intro"
            },
            {
              "label": "Module 1: ROS 2",
              "to": "/docs/module-1-ros2/overview"
            },
            {
              "label": "Module 2: Simulation",
              "to": "/docs/module-2-simulation/overview"
            },
            {
              "label": "Module 3: NVIDIA Isaac",
              "to": "/docs/module-3-isaac/overview"
            },
            {
              "label": "Module 4: VLA Integration",
              "to": "/docs/module-4-vla/overview"
            }
          ]
        },
        {
          "title": "Resources",
          "items": [
            {
              "label": "Hardware Setup",
              "to": "/docs/resources/hardware-setup"
            },
            {
              "label": "Cloud Lab",
              "to": "/docs/resources/cloud-lab"
            },
            {
              "label": "Assessments",
              "to": "/docs/resources/assessments"
            },
            {
              "label": "References",
              "to": "/docs/resources/references"
            },
            {
              "label": "FAQ",
              "to": "/docs/resources/faq"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/SHAYA9/ai-humanoid-robotics-book"
            },
            {
              "label": "Discord",
              "href": "https://discord.gg/robotics"
            },
            {
              "label": "Twitter / X",
              "href": "https://twitter.com/airoboticsbook"
            },
            {
              "label": "Stack Overflow",
              "href": "https://stackoverflow.com/questions/tagged/ros2"
            },
            {
              "label": "ROS Discourse",
              "href": "https://discourse.ros.org/"
            }
          ]
        },
        {
          "title": "Legal",
          "items": [
            {
              "label": "Privacy Policy",
              "to": "/docs/legal/privacy"
            },
            {
              "label": "Terms of Use",
              "to": "/docs/legal/terms"
            },
            {
              "label": "License",
              "to": "/docs/legal/license"
            },
            {
              "label": "Code of Conduct",
              "to": "/docs/legal/code-of-conduct"
            },
            {
              "label": "Contact",
              "to": "/docs/legal/contact"
            }
          ]
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
